blueprint:
  name: OVAPI – Helper (template sensor)
  description: >
    Template sensor that sorts upcoming rides based on
    a OVAPI REST sensor with a `Passes` attribute.
  domain: template
  homeassistant:
    min_version: 2025.12.1

  input:
    source_sensor:
      name: OVAPI REST sensor
      description: >
        REST Sensor die een Passes-attribuut bevat
      selector:
        entity:
          domain: sensor
          multiple: true
    # TimingPointCode:
    #   name: Timing Point Code
    #   description: >
    #     Een tpc is een locatie en kan bijv. een bushalte zijn. 
    #     Bushaltes aan weerszijde van de straat hebben een eigen tpc.
    #     Voor het vinden van de tpc's(Timing Point Code) gebruik:
    #     https://ovzoeker.nl/
    #   selector:
    #     text:
    lijnen:
      name: Lijnen
      description: Lijst met lijnnummer(s) of leeg laten om alle lijnen te tonen.
      default:
      selector:
        text:
          multiple: true


variables:
    source_sensors: !input source_sensor
    lijnen: !input lijnen
  
trigger:
  - platform: time_pattern
    seconds: "/15"
  - platform: state
    entity_id: !input source_sensor

sensor:
    state: OK
    attributes:
      lijnen: >-
        {{ lijnen }}
      data: >-
        {% set ns = namespace(passes={}) %}

        {% for source in source_sensors %}
          {% set p = state_attr(source, 'Passes') or {} %}
          {% set ns.passes = ns.passes | combine(p) %}
        {% endfor %}
        
        {% set data = ns.passes  | dictsort | map(attribute=1) %}
        
        {% set result = (data | selectattr('LinePublicNumber', 'in', lijnen)) if lijnen 
          else data %}

        {{ result
          | selectattr('ExpectedDepartureTime', 'defined')
          | selectattr('ExpectedDepartureTime', '>', (now() - timedelta(seconds=30)).isoformat())
          | sort(attribute='ExpectedDepartureTime')
          | list if ns.passes else []
        }}
      icon: >-
        mdi:database
