blueprint:
  name: OVAPI – Helper (template sensor)
  description: >
    Template sensor die de volgende OV-ritten sorteert op basis van
    een OVAPI REST sensor met een Passes-attribuut.
  domain: template
  homeassistant:
    min_version: 2025.12.1

  input:
    source_sensor:
      name: OVAPI REST sensor
      description: >
        REST Sensor die een Passes-attribuut bevat
      selector:
        entity:
          domain: sensor
          multiple: true
    lijnen:
      name: Lijnen
      description: Lijst met lijnnummer(s) of leeg laten om alle lijnen te tonen.
      default:
      selector:
        text:
          multiple: true


variables:
    source_sensors: !input source_sensor
    lijnen: !input lijnen
  
trigger:
  - platform: time_pattern
    minutes: "/1"
  - platform: state
    entity_id: !input source_sensor

sensor:
    state: OK
    attributes:
      lijnen: >-
        {{ lijnen }}
      data: >-
        {% set ns = namespace(passes={}) %}

        {% for source in source_sensors %}
          {% set p = state_attr(source, 'Passes') or {} %}
          {% set ns.passes = ns.passes | combine(p) %}
        {% endfor %}
        
        {% set data = ns.passes  | dictsort | map(attribute=1) %}
        
        {% set result = (data | selectattr('LinePublicNumber', 'in', lijnen)) if lijnen 
          else data %}

        {{ result
          | selectattr('ExpectedDepartureTime', 'defined')
          | selectattr('ExpectedDepartureTime', '>=', now().isoformat() )
          | sort(attribute='ExpectedDepartureTime')
          | list if ns.passes else []
        }}
      icon: >-
        mdi:database
