blueprint:
  name: OVAPI – Vertrektijden (template sensor)
  description: >
    Template sensor die de volgende OV-ritten toont op basis van
    de OVAPI helper sensor.
  domain: template
  homeassistant:
    min_version: 2025.12.1

  input:
    source_sensor:
      name: OVAPI DATA sensor
      description: >
        Sensor die een data-attribuut bevat
      selector:
        entity:
          domain: sensor
    clearing_time:
      name: clearin
      description: Time after ExpectedDepartureTime a ride will be cleared from the board
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: seconds
          mode: box

variables:
    source: !input source_sensor
    clearing_time: !input clearing_time
trigger:
  - platform: time_pattern
    seconds: "/1"
  - platform: state
    entity_id: !input source_sensor

sensor:
    state: >-
      {% set next = state_attr(source, 'data') | default([]) %}
      {% if not next %}
        Geen vertrektijden beschikbaar
      {% else %}
        {% set vertraging =
          ( as_local(as_datetime(next[0].ExpectedArrivalTime))
          - as_local(as_datetime(next[0].TargetArrivalTime))
          ).total_seconds() // 60
        %}
        {% if next[0].TripStopStatus.startswith('CANCEL') %} - min · {{ next[0].LinePublicNumber }} Rit {{ as_datetime(next[0].TargetDepartureTime).strftime('%H:%M') if next|length > 0 }} vervalt
        {% else %}
          {{ ((as_local(as_datetime(next[0].ExpectedDepartureTime)) - now()).total_seconds() // 60) | int }} min · {{ next[0].LinePublicNumber }} {{ next[0].DestinationName50 }}
          {% if vertraging > 0 %}
            (+{{ vertraging | int }})
          {% elif vertraging < 0 %}
            ({{ vertraging | int }})
          {% endif %}
        {% endif %}
      {% endif %}

    icon: >-
      {% set next = state_attr(source, 'data') | default([]) %}
      {% set t = next[0].TransportType if next else 'Unknown' %}
      {% if t == 'BUS' %}
        mdi:bus
      {% elif t == 'TRAM' %}
        mdi:tram
      {% elif t == 'METRO' %}
        mdi:subway
      {% elif t == 'TRAIN' %}
        mdi:train
      {% elif t == 'BOAT' %}
        mdi:ferry
      {% else %}
        mdi:help
      {% endif %}
    attributes:
      vertrektijd_1: >-
        {% set pos = 0 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
        {{ as_datetime(next[pos].ExpectedDepartureTime).strftime('%H:%M') if next|length > pos }}
        {% endif %}
      vertrektijd_2: >-
        {% set pos = 1 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
        {{ as_datetime(next[pos].ExpectedDepartureTime).strftime('%H:%M') if next|length > pos }}
        {% endif %}
      vertrektijd_3: >-
        {% set pos = 2 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
        {{ as_datetime(next[pos].ExpectedDepartureTime).strftime('%H:%M') if next|length > pos }}
        {% endif %}
      vertrektijd_4: >-
        {% set pos = 3 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
        {{ as_datetime(next[pos].ExpectedDepartureTime).strftime('%H:%M') if next|length > pos }}
        {% endif %}
      vertrektijd_5: >-
        {% set pos = 4 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
        {{ as_datetime(next[pos].ExpectedDepartureTime).strftime('%H:%M') if next|length > pos }}
        {% endif %}

      planning_1: >-
        {% set pos = 0 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}      
          {{ as_datetime(next[pos].TargetDepartureTime).strftime('%H:%M') if next|length > pos }}
        {% endif %}
      planning_2: >-
        {% set pos = 1 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}      
          {{ as_datetime(next[pos].TargetDepartureTime).strftime('%H:%M') if next|length > pos }}
        {% endif %}
      planning_3: >-
        {% set pos = 2 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}      
          {{ as_datetime(next[pos].TargetDepartureTime).strftime('%H:%M') if next|length > pos }}
        {% endif %}
      planning_4: >-
        {% set pos = 3 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}      
          {{ as_datetime(next[pos].TargetDepartureTime).strftime('%H:%M') if next|length > pos }}
        {% endif %}
      planning_5: >-
        {% set pos = 4 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}      
          {{ as_datetime(next[pos].TargetDepartureTime).strftime('%H:%M') if next|length > pos }}
        {% endif %}

      vertraging_1: >-
        {% set pos = 0 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
        {{  ( 
              as_local(as_datetime(next[pos].ExpectedArrivalTime)) - as_local(as_datetime(next[pos].TargetArrivalTime)) 
            ).total_seconds() // 60  if next|length > pos
        }}
        {% endif %}
      vertraging_2: >-
        {% set pos = 1 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
        {{  ( 
              as_local(as_datetime(next[pos].ExpectedArrivalTime)) - as_local(as_datetime(next[pos].TargetArrivalTime)) 
            ).total_seconds() // 60  if next|length > pos
        }}
        {% endif %}
      vertraging_3: >-
        {% set pos = 2 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
        {{  ( 
              as_local(as_datetime(next[pos].ExpectedArrivalTime)) - as_local(as_datetime(next[pos].TargetArrivalTime)) 
            ).total_seconds() // 60  if next|length > pos
        }}
        {% endif %}
      vertraging_4: >-
        {% set pos = 3 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
        {{  ( 
              as_local(as_datetime(next[pos].ExpectedArrivalTime)) - as_local(as_datetime(next[pos].TargetArrivalTime)) 
            ).total_seconds() // 60  if next|length > pos
        }}
        {% endif %}
      vertraging_5: >-
        {% set pos = 4 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
        {{  ( 
              as_local(as_datetime(next[pos].ExpectedArrivalTime)) - as_local(as_datetime(next[pos].TargetArrivalTime)) 
            ).total_seconds() // 60  if next|length > pos
        }}
        {% endif %}

      minuten_1: >-
        {% set pos = 0 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
          --
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        
        {% elif ((as_local(as_datetime(next[pos].ExpectedDepartureTime)) - now()).total_seconds()) < 60 %}
          -- min
        {% else %}
          {{ ((as_local(as_datetime(next[pos].ExpectedDepartureTime)) - now()).total_seconds() // 60) | int }} min
        {% endif%}
      minuten_2: >-
        {% set pos = 1 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
          --
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        
        {% elif ((as_local(as_datetime(next[pos].ExpectedDepartureTime)) - now()).total_seconds()) < 60 %}
          -- min
        {% else %}
          {{ ((as_local(as_datetime(next[pos].ExpectedDepartureTime)) - now()).total_seconds() // 60) | int }} min
        {% endif%}
      minuten_3: >-
        {% set pos = 2 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
          --
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        
        {% elif ((as_local(as_datetime(next[pos].ExpectedDepartureTime)) - now()).total_seconds()) < 60 %}
          -- min
        {% else %}
          {{ ((as_local(as_datetime(next[pos].ExpectedDepartureTime)) - now()).total_seconds() // 60) | int }} min
        {% endif%}
      minuten_4: >-
        {% set pos = 3 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
          --
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        
        {% elif ((as_local(as_datetime(next[pos].ExpectedDepartureTime)) - now()).total_seconds()) < 60 %}
          -- min
        {% else %}
          {{ ((as_local(as_datetime(next[pos].ExpectedDepartureTime)) - now()).total_seconds() // 60) | int }} min
        {% endif%}
      minuten_5: >-
        {% set pos = 4 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
          --
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        
        {% elif ((as_local(as_datetime(next[pos].ExpectedDepartureTime)) - now()).total_seconds()) < 60 %}
          -- min
        {% else %}
          {{ ((as_local(as_datetime(next[pos].ExpectedDepartureTime)) - now()).total_seconds() // 60) | int }} min
        {% endif%}

      lijn_1: >-
        {% set pos = 0 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
          {{ next[pos].LinePublicNumber}}
        {% endif %}
      lijn_2: >-
        {% set pos = 1 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
          {{ next[pos].LinePublicNumber}}
        {% endif %}
      lijn_3: >-
        {% set pos = 2 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
          {{ next[pos].LinePublicNumber}}
        {% endif %}
      lijn_4: >-
        {% set pos = 3 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
          {{ next[pos].LinePublicNumber}}
        {% endif %}
      lijn_5: >-
        {% set pos = 4 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
          {{ next[pos].LinePublicNumber}}
        {% endif %}

      bestemming_1: >-
        {% set pos = 0 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
          Rit {{ as_datetime(next[pos].TargetDepartureTime).strftime('%H:%M') }} vervalt
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
          {{ next[pos].DestinationName50 if next|length > 0 else '—'}}
        {% endif %}
      bestemming_2: >-
        {% set pos = 1 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
          Rit {{ as_datetime(next[pos].TargetDepartureTime).strftime('%H:%M') }} vervalt
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
          {{ next[pos].DestinationName50 if next|length > 0 else '—'}}
        {% endif %}
      bestemming_3: >-
        {% set pos = 2 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
          Rit {{ as_datetime(next[pos].TargetDepartureTime).strftime('%H:%M') }} vervalt
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
          {{ next[pos].DestinationName50 if next|length > 0 else '—'}}
        {% endif %}
      bestemming_4: >-
        {% set pos = 3 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
          Rit {{ as_datetime(next[pos].TargetDepartureTime).strftime('%H:%M') }} vervalt
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
          {{ next[pos].DestinationName50 if next|length > 0 else '—'}}
        {% endif %}
      bestemming_5: >-
        {% set pos = 4 %}
        {% set next = state_attr(source, 'data') | default([]) %}
        {% if next | length <= pos %}
        {% elif next[pos].TripStopStatus.startswith('CANCEL') %}
          Rit {{ as_datetime(next[pos].TargetDepartureTime).strftime('%H:%M') }} vervalt
        {% elif (( now() - as_local(as_datetime(next[pos].ExpectedDepartureTime)) ).total_seconds() ) > clearing_time %}
        {% else %}
          {{ next[pos].DestinationName50 if next|length > 0 else '—'}}
        {% endif %}

      status_1: >-
        {% set next = state_attr(source, 'data') | default([]) %}
        {{ next[0].TripStopStatus if next|length > 0 }}
      status_2: >-
        {% set next = state_attr(source, 'data') | default([]) %}
        {{ next[1].TripStopStatus if next|length > 1 }}
      status_3: >-
        {% set next = state_attr(source, 'data') | default([]) %}
        {{ next[2].TripStopStatus if next|length > 2 }}
      status_4: >-
        {% set next = state_attr(source, 'data') | default([]) %}
        {{ next[2].TripStopStatus if next|length > 3 }}
      status_5: >-
        {% set next = state_attr(source, 'data') | default([]) %}
        {{ next[2].TripStopStatus if next|length > 4 }}

